data_resource:
  contract:
    name: permit-to-tn-ciscolive-07
shared_services_tenant_name: shared-services
shared_services_tenant_contracts:
  - name: permit-to-core-services
  - name: permit-from-core-services
tenant_name: ciscolive-07
vrf_name: vrf-01
app_profile_name: epg-matched-esg
esg:
  esg_name: network-segments
  epg_selectors:
    - app_profile_name: network-segments
      epg_name: 10.0.71.0_24
    - app_profile_name: network-segments
      epg_name: 10.0.72.0_24
    - app_profile_name: network-segments
      epg_name: 10.0.73.0_24
    - app_profile_name: network-segments
      epg_name: 10.0.74.0_24
    - app_profile_name: network-segments
      epg_name: 10.0.75.0_24